# Generated by Django 3.0.3 on 2020-02-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_description',
            field=models.TextField(blank=True),
        ),
    ]
