# Generated by Django 3.0.3 on 2020-02-19 10:24

import contest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationmodel',
            name='hash',
            field=models.CharField(default=contest.models.generate_random_string, max_length=30),
        ),
        migrations.AlterField(
            model_name='passwordresetmodel',
            name='hash',
            field=models.CharField(default=contest.models.generate_random_string, max_length=30),
        ),
    ]
