# Generated by Django 3.0.3 on 2020-02-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='answered_questions',
            field=models.ManyToManyField(blank=True, to='contest.Question'),
        ),
    ]
