# Generated by Django 3.0.3 on 2020-03-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20200302_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='points',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
