# Generated by Django 3.0.3 on 2020-02-28 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hint',
            name='release_date',
        ),
        migrations.AddField(
            model_name='contestant',
            name='last_answered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
