# Generated by Django 3.0.3 on 2020-03-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20200229_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='image',
            field=models.ImageField(blank=True, upload_to='hints'),
        ),
    ]
