# Generated by Django 3.0.3 on 2020-03-01 08:44

import contest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20200301_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='image',
            field=models.ImageField(blank=True, upload_to=contest.models.get_unique_name),
        ),
    ]
